theme: jekyll-theme-minimal
title: [Abel Sandoval Gonzalez]
description: ['<p> <b>About Me</b> <br> Hello! I graduated from The University of Texas at Austin with a B.S.A. in Neuroscience, B.S. in Public Health, and a Certificate in Elements of Computing. <br> <a href='https://www.linkedin.com/in/abel-sandoval-gonzalez/'>LinkedIn</a> </p>']
